spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

accounts:
  message: "myBank QA"
  contactDetails:
    name: "uday"
    email: "uday.shastrakar@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345